language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: clang   
    addons:
      apt:
        packages:
          - mesa-vulkan-drivers 

  - os: linux
    dist: xenial
    env: 
      - COVERAGE=true
    addons:
      apt:
        packages:
          - mesa-vulkan-drivers
      sonarcloud:
        organization: "mualphaomegaepsilon-github"

  - os: osx
    osx_image: xcode10.2

  - os: windows
    filter_secrets: false

script:
- if [ -n "${COVERAGE:-}" ]; then ./scripts/shellcheck.sh; fi  
- if [ -n "${SONAR_SCANNER_HOME:-}" ]; then git fetch --unshallow || echo "No need to unshallow"; fi
- if [ -n "${COVERAGE:-}" ]; then sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
- if [ "${TRAVIS_OS_NAME}" == "windows" ]; then choco install python3 -y; PY_PYTHON=3 && export PY_PYTHON; fi
- ./tests/setup.sh
- ./tests/build.sh
- ./tests/run.sh
- if [ -n "${SONAR_SCANNER_HOME:-}" ]; then sonar-scanner; fi
- cd tests/build/ && ./test_initializeVulkan && echo $?
