language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: clang
    addons:
      apt:
        packages:
          - mesa-vulkan-drivers

  - os: linux
    dist: xenial
    compiler: g++
    env: 
      - COVERAGE=true
    addons:
      apt:
        packages:
          - mesa-vulkan-drivers
      sonarcloud:
        organization: "mualphaomegaepsilon-github"

  - os: osx
    osx_image: xcode10.2

  - os: windows

before-install:
- if [ -n "${COVERAGE:-}" ]; then ./scripts/shellcheck.sh; fi  

install:
- ./scripts/installVulkan.sh

before-script:
- vulkaninfo

script:
- if [ -n "${SONAR_SCANNER_HOME:-}" ]; then git fetch --unshallow || echo "No need to unshallow"; fi
- if [ -n "${COVERAGE:-}" ]; then sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
- ./tests/setup.sh
- ./tests/build.sh
- ./tests/run.sh
- if [ -n "${SONAR_SCANNER_HOME:-}" ]; then sonar-scanner; fi
- cd tests/build/ && ./test_initializeVulkan && echo $?
