language: cpp
dist: xenial
git:
  depth: 1
  submodules: false

matrix:
  include:
  
  - os: linux
    compiler: gcc  
    git:
      depth: false
    env: 
    - CMAKE_ARGS="-DCOVERAGE_FLAG=--coverage -DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_WAYLAND_SUPPORT=OFF"
    - CMAKE_BUILD_WRAPPER="build-wrapper-linux-x86-64 --out-dir ."    
    addons:
      apt:
        packages: mesa-vulkan-drivers
      sonarcloud:
        organization: "mualphaomegaepsilon-github"
    before_script:
    - sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov
    after_script:
    - sonar-scanner
        
  - os: linux
    compiler: clang
    env:
    - CMAKE_ARGS="-DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_WAYLAND_SUPPORT=OFF"
    addons:
      apt:
        packages: mesa-vulkan-drivers
    
  - os: osx
    osx_image: xcode11
    env: 
    - CMAKE_ARGS="-DCMAKE_OSX_DEPLOYMENT_TARGET=10.14"
  
  - os: windows
    install: 
    - choco install windowsdriverkit10


script:
- git submodule update --init --recursive --depth 1
- mkdir -p tests/build && cd tests/build
- cmake .. ${CMAKE_ARGS}
- ${CMAKE_BUILD_WRAPPER} cmake --build .
# Only test runtime under Linux, since osx is missing Metal
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ctest -j2; fi
