language: cpp
dist: bionic
# git:
#   depth: false

matrix:
  include:
  
  - os: linux
    env: COVERAGE=true
    addons:
      apt:
        packages: libvulkan-dev mesa-vulkan-drivers vulkan-utils
      sonarcloud:
        organization: "mualphaomegaepsilon-github"
    before_script:
    - sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov
    after_script:
    - sonar-scanner
        
  - os: linux
    compiler: clang
    addons:
      apt:
        packages: libvulkan-dev mesa-vulkan-drivers vulkan-utils
    
  - os: osx
    osx_image: xcode11

script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/shellcheck.sh; fi
- ./scripts/installVulkan.sh
- ./tests/setup.sh
- ./tests/build.sh
- ./tests/run.sh
- cd tests/build/ && ./test_initializeVulkan && echo $?
