language: cpp
dist: xenial
addons:
      apt:
        packages:
          - mesa-vulkan-drivers

matrix:
  include:
  - os: linux
    compiler: clang    

  - os: linux
    env: 
      - COVERAGE=true
    addons:
      sonarcloud:
        organization: "mualphaomegaepsilon-github"

  - os: osx
    osx_image: xcode10.2

  - os: windows
    python: "3.6"

script:
- if [ -n "${COVERAGE:-}" ]; then ./scripts/shellcheck.sh; fi  
- ./scripts/installVulkan.sh
- if [ -n "${SONAR_SCANNER_HOME:-}" ]; then git fetch --unshallow || echo "No need to unshallow"; fi
- if [ -n "${COVERAGE:-}" ]; then sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
- ./tests/setup.sh
- ./tests/build.sh
- ./tests/run.sh
- if [ -n "${SONAR_SCANNER_HOME:-}" ]; then sonar-scanner; fi
- cd tests/build/ && ./test_initializeVulkan && echo $?
