language: cpp
dist: bionic
git:
  submodules: false
  depth: false

matrix:
  fast_finish: true
  include:
  
  - os: linux
    name: GCC (sonar-scanner)
    env: 
    - CMAKE_ARGS="-DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_WAYLAND_SUPPORT=OFF"
    - CMAKE_BUILD_WRAPPER="build-wrapper-linux-x86-64 --out-dir ."    
    - LIBINTERCEPTOR_DIR="/home/travis/.sonar/cache/681277d525b6e4c5ed5e6c2a429caa64/build-wrapper-linux-x86"  
    addons:
      apt:
        packages: mesa-vulkan-drivers
      sonarcloud:
        organization: "mualphaomegaepsilon-github"
    before_script: 
    - cp "${LIBINTERCEPTOR_DIR}"/libinterceptor-x86_64.so "${LIBINTERCEPTOR_DIR}"/libinterceptor-haswell.so 
    after_script: cd ../.. && sonar-scanner > /dev/null
    
  - os: osx
    name: Clang
    osx_image: xcode11
  
  - os: windows
    name: MSVC
    env: 
    - CMAKE_ARGS="-DWDK_FULL_PATH=C:/Users/travis/build/MuAlphaOmegaEpsilon/vengine/libs/wdk-10 -DCMAKE_SUPPRESS_REGENERATION=ON"
    - CMAKE_BUILD_ARGS="-- -nologo -verbosity:minimal"
    before_script: 
    - git submodule update --init --depth 1 --remote libs/wdk-10

script:
- git submodule update --init --depth 1 --remote libs/Vulkan-Headers
- git submodule update --init --depth 1 --remote libs/Vulkan-Loader
- mkdir -p tests/build && cd tests/build
- cmake .. ${CMAKE_ARGS}
- ${CMAKE_BUILD_WRAPPER} cmake --build . ${CMAKE_BUILD_ARGS}
