language: cpp

dist: xenial

matrix:
  fast_finish: true
  include:

    - os: linux
      compiler: clang  
      addons:
        apt:
          packages:
          - libvulkan-dev
          - mesa-vulkan-drivers
          - vulkan-utils

    - os: linux
      compiler: g++
      env: 
        - COVERAGE=true
      addons:
        apt:
          packages:
          - libvulkan-dev
          - mesa-vulkan-drivers
          - vulkan-utils
        sonarcloud:
          organization: "mualphaomegaepsilon-github"

    - os: osx

    - os: windows

script:
  - if [ -n "${SONAR_SCANNER_HOME:-}" ]; then git fetch --unshallow || echo "No need to unshallow"; fi
  - if [ -n "${COVERAGE:-}" ]; then ./tests/shellcheck.sh; fi
  - if [ -n "${COVERAGE:-}" ]; then sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
  - ./tests/setup.sh
  - ./tests/build.sh
  - ./tests/run.sh
  - if [ -n "${SONAR_SCANNER_HOME:-}" ]; then sonar-scanner; fi
  - cd tests/build/ && ./test_initializeVulkan && echo $?
