language: cpp

matrix:
  include:
  
  - os: linux
    dist: xenial
    env: 
      - COVERAGE=true
    addons:
      apt:
        packages:
          - mesa-vulkan-drivers
      sonarcloud:
        organization: "mualphaomegaepsilon-github"
    before_script:
    - git fetch --unshallow || echo "No need to unshallow"
    - ./scripts/shellcheck.sh
    - sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov
    after_script:
    - sonar-scanner
        
  - os: linux
    dist: xenial
    compiler: clang   
    addons:
      apt:
        packages:
          - mesa-vulkan-drivers 

  - os: osx
    osx_image: xcode10.2

script:
- ./scripts/shellcheck.sh  
- if [ -n "${SONAR_SCANNER_HOME:-}" ]; then git fetch --unshallow || echo "No need to unshallow"; fi
- if [ -n "${COVERAGE:-}" ]; then sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov; fi
- ./scripts/installVulkan.sh
- ./tests/setup.sh
- ./tests/build.sh
- ./tests/run.sh
- cd tests/build/ && ./test_initializeVulkan && echo $?
