name: CMake C++ CI
on: [push]

jobs:
  build:
    name: GCC - Linux
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      # env:
        # CMAKE_ARGS: -DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_WAYLAND_SUPPORT=OFF
        # CMAKE_BUILD_WRAPPER: build-wrapper-linux-x86-64 --out-dir .  
      run: echo Hello world
        # mkdir -p tests/build && cd tests/build |
        # cmake .. ${CMAKE_ARGS} |
        # cmake --build . ${CMAKE_BUILD_ARGS} |
      # uses: sonarsource/sonarcloud-github-action@master
