name: CMake C++ CI
on: [push]

runs-on: ${{matrix.os}}
jobs:
  strategy:
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      include:
      - os: ubuntu-latest
        env: STRING="Ubuntu"
      - os: macos-latest
        env: STRING="OSX"
      - os: windows-latest
        env: STRING="Windows"

      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Trying to echo env
        run: echo ${STRING}
        