name: CMake C++ CI
on: [push]

jobs:
  build:
    name: GCC - Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with: 
        fetch-depth: 1
    - name: Pull submodules
      run: git submodule update --init libs/Vulkan-Headers libs/Vulkan-Loader
    - name: Configure build
      run: |
        mkdir -p tests/build
        cd tests/build
        cmake .. -DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_WAYLAND_SUPPORT=OFF
    - name: Build
      run: cmake --build . --parallel
    - uses: sonarsource/sonarcloud-github-action@master



# cmake --build . ${CMAKE_BUILD_ARGS} | 
# env:
# CMAKE_ARGS: -DBUILD_WSI_XCB_SUPPORT=OFF -DBUILD_WSI_XLIB_SUPPORT=OFF -DBUILD_WSI_WAYLAND_SUPPORT=OFF
# CMAKE_BUILD_WRAPPER: build-wrapper-linux-x86-64 --out-dir .  
# run: echo Hello world

# uses: sonarsource/sonarcloud-github-action@master
